# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('santec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopitaux',
            name='Nom_Hopital',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hopitaux',
            name='id_adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossier',
            name='id_antecedant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='santec.Antecedant'),
        ),
    ]
